# Generated by Django 6.0.6 on 2026-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemetadata',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', help_text='Current validity status of the certificate', max_length=10),
        ),
    ]
